### PR TITLE
Updated definition of header P-Access-Network-Info according to RFC 7…

### PR DESCRIPTION
**Pull request by BarfCliff**
…315, section 5.4.

### CODE REVIEW

**Comment by sgodin** [comment]
Thank you for this contribution.  It looks good to me, but it would be ideal if we had a test case for the case.  Would you mind adding encode/decode tests for this change to resip/stack/test/testSipMessage.cxx?

**Comment by BarfCliff** [comment]
Ok, I'll give it a try.

**Comment by sgodin** [comment]
Great stuff - thanks!

**Comment by BarfCliff** [comment]
Finally I could contribute with something, although a small part.

**Pull request merged**
