### PR TITLE
TLS on windows

### PR DESCRIPTION
**Pull request by renaud-sc**
- Fix certificate path construction and Windows
- Fix various typos

### CODE REVIEW

**Comment by sgodin** [comment]
Thanks Renaud!  I was under the impression that windows doesn't really care if you use / or \ as a path separator.  What error were you seeing before this fix?

**Comment by renaud-sc** [comment]
You are right, I must have seen exceptions due to invalid certificates and confused myself.. However I think this improves the implementation.

**Review by SamyDgz — APPROVED** [review]

**Comment by sgodin** [comment]
I have cherry picked all the spelling correction changes and left the path separator changes out.  Thanks the the contribution.

**Comment by sgodin** [comment]
Closing.

**Pull request closed without merging**
