### PR TITLE
Update Helper.cxx

### PR DESCRIPTION
**Pull request by bogdanvasilescu-opentext**
Added missing CR LF sequence at the end of the start line.

### CODE REVIEW

**Comment by bogdanvasilescu-opentext** [comment]
This change addresses issue #225

**Comment by sgodin** [comment]
Wow!  Nice find.  I'm having trouble grasping why this hasn't been noticed before.  It seems that many 100 responses and some 503 responses that the stack generates uses this code.  May I ask how you noticed this?

**Comment by bogdanvasilescu-opentext** [comment]
Hello @sgodin,

I was trying to see how the stack would handle a burst of new sessions (by firing 100 new invite sessions, immediately one after the other :D) using the repro app as proxy. 
In the sip messages log it looked like some of these invites were not receiving a response. After checking the main log I discovered these 503 responses where the stack was complaining about missing VIA header (although it was there). Eventually I realized that there was a problem with the message itself and not with the way it was logged.

**Comment by sgodin** [comment]
Thanks for the explanation.  Very interesting.  :)

**Pull request merged**
