### PR TITLE
Multiple crash scenarios involving the offer/answer state and an inco…

### LINKED ISSUE #140: Multiple crash scenarios involving the offer/answer state and an incoming request
1, Target refresh in the wrong invitesession state causes abort
(this was described in detail in the mailing list but was not concluded, see
https://list.resiprocate.org/archive/resiprocate-devel/msg09021.html
https://list.resiprocate.org/archive/resiprocate-devel/msg09022.html
https://list.resiprocate.org/archive/resiprocate-devel/msg09023.html
)
2, In case of SDP-less reINVITE, after receiving an offer, but failing to call provideAnswer() immediately (because for example, in case of a B2BUA, the other leg has to answer first), meanwhile receiving an UPDATE, InviteSession triggers an assert.

Both cases can be remedied by a well-placed 491.

### PR DESCRIPTION
**Pull request by szokovacs**
…ming request

fixes #140

### CODE REVIEW

**Comment by dpocock** [comment]
@sgodin do you feel this is correct and that it has been inserted at the right place?

**Comment by sgodin** [comment]
Thank you for the contribution! 

I see what this solution is trying to accomplish, but it is doing so outside of the InviteSession state machine.  There is already code in the state machine to accomplish the same thing.  ie:  See code in InviteSession::dispatchSentUpdate where a 491 response is sent.  It is confusing to have handling for this type of thing in two different places.  Handling in the state machine itself was the intended path for this type of thing.

@szokovacs Do you now exactly what scenarios were causing problems for you?  If so, we should be able to address this directly in the statemachine handling methods.

**Comment by szokovacs** [comment]
Hi,
As I mentioned in
https://list.resiprocate.org/archive/resiprocate-devel/msg09023.html
the problem is with target refresh:
your patch in
https://list.resiprocate.org/archive/resiprocate-devel/msg09022.html
fixes the crash in dispatchOthers()
(all the other states mentioned in the proposed isUpdating() are handled correctly in their respective dispatch*() ), but it is too late, the contact is already overwritten.
It is actually mentioned in the comment in Dialog::handleTargetRefresh().

**Comment by sgodin** [comment]
Thanks for the reminder.  :)  I think we need to go down one of the
following 2 paths:
1.  Figure out a solution for the target update problem, and handle in the
state machine as designed.     OR
2.  Use your solution, but remove all the state handling logic that will no
longer get used because of it.

I need some more time to ponder this.

Thanks,
Scott

**Comment by szokovacs** [comment]
After discussing Scott, we agreed to go with a different solution.

**Pull request closed without merging**
